---
title: Adam's Theme
output:
  html_document:
    highlight: adam.theme
    css: css/base.css
    md_extensions: -smart
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  echo=TRUE, message=FALSE, warning=FALSE,
  dev="svglite", fig.align="center"
)

old.hooks <- fansi::set_knit_hooks(knitr::knit_hooks)

styles <- c(
  getOption('fansi.style'),
  "PRE.fansi CODE {background-color: transparent;}",
  "PRE.fansi-error {background-color: transparent;}",
  "PRE.fansi-warning {background-color: transparent;}",
  "PRE.fansi-message {background-color: transparent;}"
)

old.hooks <- c(
  old.hooks,
  fansi::set_knit_hooks(
    knitr::knit_hooks,
    which=c('warning', 'error', 'message'),
    style=styles
  )
)

options(crayon.enabled = TRUE)
```

# Packages

```{r}
library(tidyverse)
theme_set(theme_bw())
```

# Penguins data

```{r}
penguins <- palmerpenguins::penguins %>%
  drop_na()

glimpse(penguins)
```

```{r}
new_peng <- penguins %>%
  mutate(diff1 = bill_length_mm - mean(bill_length_mm)) %>%
  group_by(species, island) %>%
  mutate(diff2 = bill_length_mm - mean(bill_length_mm)) %>%
  ungroup() %>%
  select(species, island, bill_length_mm, contains("diff"))

new_peng
```

```{r, fig.width=12}
ggplot(penguins, aes(x=bill_length_mm, y=bill_depth_mm)) +
  geom_point(aes(colour=species)) +
  facet_wrap(~species, nrow=1) +
  labs(x="Bill length (mm)", y="Bill depth (mm)")
```

# Everything else

```{r, eval=FALSE}
# This chunk starts with a comment

if else while for 
TRUE FALSE NA NULL

# Quoted variables:
`s2@_df` <- 3

1 2 3 4 5 6 7 8 9 10
```
